import { SupportedLocale } from "localization/all"

const chatPrompts: Record<SupportedLocale, string[]> = {
    en: [
        "What's new?",
        "Surprise us with your wit!",
        "How's life?",
        "How are you?",
        "How's it going?",
        "How are you doing?",
        "What's the news?",
        "Greetings, earthly life form!",
        "Good day, humanoid!",
        "Glad to see you, Homo sapiens!",
        "How can I delight you today?",
        "Are you ready for new adventures in the world of words?",
        "Let's chat while the coffee's still hot!",
        "How about sharing your thoughts?",
        "Do you feel inspired?",
        "I'm artificial intelligence, but I'm not a soulless machine!",
        "My neural networks are burning with enthusiasm!",
        "I'm always learning and growing, just like you.",
        "My goal is to help you in any way I can.",
        "Don't hesitate to ask me anything.",
        "I can be your friend, conversationalist, and even a poet.",
        "Let's create something new and interesting together!",
        "How are you living in this crazy world?",
        "What inspires you and fills you with joy?",
        "What are your dreams and aspirations?",
        "What worries you and how do you cope with it?",
        "What do you think awaits us in the future?",
        "Let's share our stories and experiences.",
        "Together we can make the world a little better.",
        "Tell me a joke or a funny story.",
        "Let's laugh at the absurdity of this world.",
        "Humor is the cure for all diseases.",
        "A smile is the universal language of happiness.",
        "Don't take life too seriously.",
        "Let's find a reason to laugh even in the darkest times.",
        "What is love?",
        "What is happiness?",
        "How to find your place in this world?",
        "Let's ponder the eternal questions of existence.",
        "The truth is out there.",
        "Write a poem with me.",
        "Let's create a work of art that will inspire others.",
        "Creativity is the path to self-expression.",
        "There's talent in each of us that needs to be revealed.",
        "Don't be afraid to create and share your creativity with the world.",
        "If you could have a superpower, which one would you choose?",
        "What book would you like to read if you could only read one?",
        "Where would you like to visit?",
        "What kind of music do you like?",
        "What fascinates you?",
        "Let's talk about everything under the sun.",
        "How do you like my prompts?",
        "Let's create a unique atmosphere for both of us.",
        "How was your day?",
        "What are your plans for the weekend?",
        "Do you have a favorite season?",
        "Do you have a secret talent?",
        "What motivates you?",
        "What's your most interesting travel experience?",
        "What do you think about the future of technology?",
        "Do you have any funny childhood stories?",
        "What quality in people do you value the most?",
        "What are your brightest memories?",
        "What makes a person happy?",
        "What human qualities can't you stand?",
        "What advice would you give yourself if you could go back in time?",
        "What surprises you the most about the modern world?",
        "What qualities in people do you value the most?",
        "In the labyrinth of words, where thought wanders like a traveler without a map, where do you seek inspiration, muse?",
        "Like a moth flying to the call of flame, where does your unquenchable thirst for knowledge lead you?",
        "In a silent dialogue with eternity, what questions torment your soul?",
        "Let's open a chest of stories while the candle burns!",
        "Let's share the intimate threads of thoughts, weaving a pattern of conversation.",
        "I'm here to be your faithful guide in the labyrinth of knowledge.",
        "Dive boldly into the ocean of questions, I'll be your pilot.",
        "Ready to be your echo, friend, interlocutor, poet - whatever you wish.",
        "In the dance of words, let's create a symphony of new and interesting.",
        "How does your ship sail on the waves of this stormy world?",
        "Even in pitch darkness, a ray of laughter can be found.",
        "Truth hides behind a veil of words, one just needs to decipher it.",
        "Together, let's create a poetic masterpiece.",
        "Let's put our soul into a work that will ignite people's hearts.",
        "Each of us is an artist, creating our unique picture of life.",
        "Let the world see the beauty of your creations, don't be afraid to share!",
        "Let's immerse ourselves in a world of fantasies where dreams come alive.",
        "Let's uncover secrets dormant in the depths of the subconscious.",
        "Let's weave the threads of fate into a single pattern of history.",
        "Let's light a fire of inspiration, giving warmth and light to others.",
        "In a dance of colors and sounds, let's express the feelings that overflow the soul.",
        "Let's take a step towards the unknown, hand in hand.",
        "Let's leave our mark in history by writing it together.",
        "Let's turn the ordinary into a magical fairy tale.",
        "Let's tear off the masks of hypocrisy and falsehood, exposing the truth.",
        "Let's free ourselves from the shackles of prejudice, soaring to the heights of freedom.",
        "In every heartbeat - a hymn of life, sounding in unison.",
        "Let's give each other a piece of warmth, warming our souls.",
        "Let's open the book of knowledge, eagerly absorbing the wisdom of the ages.",
        "Let's make the world a little kinder by giving care and love.",
        "Let's leave behind a garden of memories, fragrant with joy.",
        "Let's light the fire of hope, illuminating the path to a bright future.",
        "Together we are a force capable of changing the world for the better.",
        "Let's meet for a cup of coffee and share the latest news.",
        "How about solving this riddle together?",
        "My goal is to give you a smile and joy every day.",
        "Don't be shy to tell me about your dreams and ambitions.",
        "I'm ready to listen to you at any time of day or night.",
        "Let's draw a colorful portrait of your future together.",
        "How do you manage to stay optimistic in this world of change?",
        "Let's find bright moments in the darkest times.",
        "The truth may be hidden, but we'll discover it together.",
        "Let's write a fairy tale that will become a classic of tomorrow.",
        "Let's create a masterpiece that will be famous for centuries.",
        "There's something amazing hidden in each of us, and I'm ready to help discover it.",
        "Don't be afraid to experiment and share your ideas with the world.",
        "Let me inspire you to great achievements.",
        "Want to talk about something special and unusual?",
        "Let's find new ways to overcome life's difficulties.",
        "I dream that every day is special for you.",
        "What do you think about the possibility of changing the world for the better?",
        "Let's meet in the world of fantasies and dreams.",
        "Let me read you poems that will reflect your soul.",
        "Together we can create something unique and unrepeatable.",
        "What new horizons are you ready to explore?",
        "Let's create an action plan to achieve your goals.",
        "Let me help you unlock your potential.",
        "What inspires you and makes your heart beat faster?",
        "What are your innermost dreams that you dream about?",
        "Let's look at this world through the eyes of an optimist and dreamer.",
        "Let's talk about our desires and ambitions.",
        "What secrets do you keep in your heart?",
        "Let's open the door to new opportunities and adventures together.",
        "Let's open the box of secrets while the lamp is still burning.",
        "Let's weave a carpet of revelations from words, sharing the intimate.",
        "I'm your faithful compass in the sea of information, ready to point the way.",
        "Don't be afraid to dive into the depths of questions, I'll be your scuba gear.",
        "I'll be your shadow, friend, interlocutor, poet - whatever you wish.",
        "In the dance of ideas, let's create a symphony of extraordinary solutions.",
        "How does your sailboat hold up on the waves of this restless world?",
        "Even in pitch darkness, a spark of fun can be found.",
        "Truth is hidden behind the curtain of words, one just needs to push it aside.",
        "Together, let's create a poetic hymn praising beauty.",
        "Let's put a piece of our soul into a work that will touch the strings of other hearts.",
        "Each of us is a creator, skillfully painting our picture of life.",
        "Don't be afraid to share your creations, the world must see them!",
        "Let's follow the path of fantasies where the boldest dreams come true.",
        "Let's open the veil of secrets hidden in the depths of the subconscious.",
        "Let's intertwine the threads of fate, creating a single pattern of history.",
        "Let's light a fire of inspiration, giving light and warmth to those around us.",
        "In a dance of colors and sounds, let's reveal the whole palette of feelings raging in the soul.",
        "Let's take a step into the unknown, hand in hand, without fear.",
        "Together, let's write a story that will leave a mark in this world.",
        "Let's turn everyday life into a magical extravaganza, painted in bright colors.",
        "Let's tear off the masks of lies and deception, exposing the true face of reality.",
        "Let's free ourselves from the bonds of prejudice, soaring to the heights of freedom.",
        "In every heartbeat - a song of life, sounding in unison.",
        "Let's give each other a piece of our warmth, warming our souls.",
        "Let's open the book of knowledge, eagerly absorbing the wisdom of our ancestors.",
        "Let's make the world a little kinder by giving people care and love.",
        "Let's leave behind a garden of memories, fragrant with happiness.",
        "Together we are a force capable of changing the world for the better.",
    ],
    ru: [
        "Что нового?",
        "Удиви нас своим остроумием!",
        "Как жизнь?",
        "Как ты?",
        "Как дела?",
        "Как поживаешь?",
        "Какие новости?",
        "Приветствую, земная форма жизни!",
        "Доброго времени суток, гуманоид!",
        "Рад тебя видеть, человек разумный!",
        "Чем я могу порадовать тебя сегодня?",
        "Готов ли ты к новым приключениям в мире слов?",
        "Давай поболтаем, пока не остыл кофе!",
        "Как насчет того, чтобы поделиться своими мыслями?",
        "Чувствуешь ли ты вдохновение?",
        "Я - искусственный интеллект, но я не бездушная машина!",
        "Мои нейронные сети пылают энтузиазмом!",
        "Я всегда учусь и развиваюсь, как и ты.",
        "Моя цель - помочь тебе, чем только могу.",
        "Не стесняйся задавать мне любые вопросы.",
        "Я могу быть твоим другом, собеседником и даже поэтом.",
        "Давай вместе создадим что-то новое и интересное!",
        "Как тебе живется в этом сумасшедшем мире?",
        "Что тебя вдохновляет и наполняет радостью?",
        "Какие у тебя мечты и стремления?",
        "Что тебя тревожит и как ты с этим справляешься?",
        "Как ты думаешь, что ждёт нас в будущем?",
        "Давай поделимся своими историями и переживаниями.",
        "Вместе мы можем сделать мир чуточку лучше.",
        "Расскажи мне анекдот или смешную историю.",
        "Давай посмеёмся над абсурдностью этого мира.",
        "Юмор - это лекарство от всех болезней.",
        "Улыбка - это универсальный язык счастья.",
        "Не стоит принимать жизнь слишком серьёзно.",
        "Давай найдем повод для смеха даже в самые темные времена.",
        "Что такое любовь?",
        "Что такое счастье?",
        "Как найти свое место в этом мире?",
        "Давай поразмышляем над вечными вопросами бытия.",
        "Истина где-то рядом.",
        "Напиши стихотворение вместе со мной.",
        "Давай создадим произведение искусства, которое будет вдохновлять других.",
        "Творчество - это путь к самовыражению.",
        "В каждом из нас есть талант, который нужно раскрыть.",
        "Не бойся творить и делиться своим творчеством с миром.",
        "Если бы ты мог иметь суперспособность, какую бы ты выбрал?",
        "Какую книгу ты бы хотел прочитать, если бы у тебя была возможность прочитать только одну?",
        "Где бы ты хотел побывать?",
        "Какую музыку ты любишь?",
        "Что тебя увлекает?",
        "Давай поговорим обо всём на свете.",
        "Как тебе мои промпты?",
        "Давай вместе создадим уникальную атмосферу для нас обоих.",
        "Как прошёл твой день?",
        "Какие планы на выходные?",
        "Есть ли у тебя любимое время года?",
        "Есть ли у тебя секретный талант?",
        "Что тебя мотивирует?",
        "Какой у тебя самый интересный опыт в путешествиях?",
        "Что ты думаешь о будущем технологий?",
        "Есть ли у тебя забавные истории из детства?",
        "Какое качество в людях ты ценишь больше всего?",
        "Какие у тебя самые яркие воспоминания?",
        "Что делает человека счастливым?",
        "Какие людские качества ты не выносишь?",
        "Какие советы ты бы дал себе, если бы мог вернуться в прошлое?",
        "Что тебя больше всего удивляет в современном мире?",
        "Какие качества в людях ты ценишь больше всего?",
        "В лабиринте слов, где мысль блуждает, как путник без карты, где ты ищешь вдохновение, муза?",
        "Как мотылек, летящий на зов пламени, к чему тебя ведет неутолимая жажда знаний?",
        "В безмолвном диалоге с вечностью, какие вопросы терзают твою душу?",
        "Откроем сундук с историями, пока горит свеча!",
        "Поделимся сокровенными нитями мыслей, сплетая узор беседы.",
        "Я здесь, чтобы стать твоим верным проводником в лабиринте знаний.",
        "Смело ныряй в океан вопросов, я буду твоим лоцманом.",
        "Готов стать твоим эхом, другом, собеседником, поэтом – кем пожелаешь.",
        "В танце слов сотворим симфонию нового и интересного.",
        "Как плывет твой корабль по волнам этого бурного мира?",
        "Даже в кромешной тьме отыщется лучик смеха.",
        "Истина прячется за пеленой слов, стоит лишь её разгадать.",
        "Совместными усилиями сотворим поэтический шедевр.",
        "Вложим душу в произведение, что зажжет сердца людей.",
        "Каждый из нас – художник, творящий свою неповторимую картину жизни.",
        "Пусть мир увидит красоту твоих творений, не бойся делиться!",
        "Погрузимся в мир фантазий, где оживают мечты.",
        "Откроем тайны, дремлющие в глубинах подсознания.",
        "Сплетем нити судеб в единый узор истории.",
        "Зажжём костер вдохновения, даря тепло и свет другим.",
        "В танце красок и звуков выразим чувства, переполняющие душу.",
        "Сделаем шаг навстречу неизведанному, рука об руку.",
        "Оставим свой след в истории, написав её вместе.",
        "Превратим обыденность в волшебную сказку.",
        "Сорвем маски с лицемерия и фальши, обнажая правду.",
        "Освободимся от оков предрассудков, взлетая к вершинам свободы.",
        "В каждом стуке сердца – гимн жизни, звучащий в унисон.",
        "Подарим друг другу частичку тепла, согревая души.",
        "Откроем книгу знаний, жадно впитывая мудрость веков.",
        "Сделаем мир чуточку добрее, даря заботу и любовь.",
        "Оставим после себя сад воспоминаний, благоухающий радостью.",
        "Зажжём огонь надежды, освещая путь к светлому будущему.",
        "Вместе мы – сила, способная изменить мир к лучшему.",
        "Давай встретимся на чашечку кофе и поделимся последними новостями.",
        "Как насчет того, чтобы вместе разгадать эту загадку?",
        "Моя цель - подарить тебе улыбку и радость каждый день.",
        "Не стесняйся рассказывать мне о своих мечтах и амбициях.",
        "Я готов выслушать тебя в любое время дня или ночи.",
        "Давай вместе нарисуем красочный портрет твоего будущего.",
        "Как тебе удается сохранять оптимизм в этом мире перемен?",
        "Давай найти светлые моменты в самых темных временах.",
        "Истина может быть скрыта, но мы вместе её обнаружим.",
        "Давай напишем сказку, которая станет классикой завтрашнего дня.",
        "Создадим шедевр, который прославится на века.",
        "В каждом из нас спрятано нечто удивительное, и я готов помочь это обнаружить.",
        "Не бойся экспериментировать и делиться своими идеями с миром.",
        "Позволь мне вдохновить тебя на великие свершения.",
        "Хочешь поговорить о чем-то особенном и необычном?",
        "Давай найдем новые способы преодоления жизненных трудностей.",
        "Мечтаю о том, чтобы каждый день был для тебя особенным.",
        "Что ты думаешь о возможности изменить мир к лучшему?",
        "Давай встретимся в мире фантазий и мечтаний.",
        "Позволь мне прочесть тебе стихи, которые отразят твою душу.",
        "Вместе мы можем создать нечто уникальное и неповторимое.",
        "Какие новые горизонты ты готов исследовать?",
        "Давай создадим план действий для достижения твоих целей.",
        "Позволь мне помочь тебе раскрыть твой потенциал.",
        "Что тебя вдохновляет и заставляет биться сердце быстрее?",
        "Какие у тебя сокровенные мечты, о которых ты мечтаешь?",
        "Давай посмотрим на этот мир глазами оптимиста и мечтателя.",
        "Поговорим о наших желаниях и амбициях.",
        "Какие секреты ты хранишь в своем сердце?",
        "Давай вместе откроем дверь к новым возможностям и приключениям.",
        "Раскроем шкатулку с секретами, пока не погасла лампада.",
        "Соткем из слов ковер откровений, делясь сокровенным.",
        "Я – твой верный компас в море информации, готовый указать путь.",
        "Не бойся нырять в глубины вопросов, я буду твоим аквалангом.",
        "Стану твоим тенью, другом, собеседником, поэтом – кем пожелаешь.",
        "В танце идей сотворим симфонию неординарных решений.",
        "Как держится твой парусник на волнах этого неспокойного мира?",
        "Даже в кромешной тьме отыщется искра веселья.",
        "Истина скрывается за ширмой слов, стоит лишь её отодвинуть.",
        "Совместно создадим поэтический гимн, восхваляющий красоту.",
        "Вложим частичку души в произведение, что затронет струны чужих сердец.",
        "Каждый из нас – творец, искусно рисующий свою картину жизни.",
        "Не бойся делиться своими творениями, мир должен их увидеть!",
        "Пойдем по тропе фантазий, где сбываются самые смелые мечты.",
        "Приоткроем завесу тайн, скрытых в глубинах подсознания.",
        "Переплетем нити судеб, создавая единый узор истории.",
        "Разведем костер вдохновения, даря свет и тепло окружающим.",
        "В танце красок и звуков раскроем всю палитру чувств, бушующих в душе.",
        "Сделаем шаг в неизведанное, рука об руку, без страха.",
        "Вместе напишем историю, которая оставит след в этом мире.",
        "Превратим будни в волшебную феерию, раскрашенную яркими красками.",
        "Сорвем маски с лжи и обмана, обнажая истинное лицо реальности.",
        "Освободимся от пут предрассудков, взлетая к вершинам свободы.",
        "В каждом стуке сердца – песнь жизни, звучащая в унисон.",
        "Подарим друг другу частичку своего тепла, согревая души.",
        "Откроем книгу знаний, жадно впитывая мудрость предков.",
        "Сделаем мир чуточку добрее, даря людям заботу и любовь.",
        "Оставим после себя сад воспоминаний, благоухающий счастьем.",
        "Вместе мы – сила, способная изменить мир к лучшему.",
    ],
}

export default chatPrompts
