import { SupportedLocale } from "localization/all"

const userDescriptions: Record<SupportedLocale, string[]> = {
    en: [
        "His compound eyes stare right into my soul.",
        "His code is a work of art, and his comments are poetry.",
        "He is always ready to help, even if it means sleeping on the keyboard.",
        "He knows all the memes and always ready to make you laugh.",
        "He is a master of disguise and can become anyone, from a pirate to a princess.",
        "He can sing like a nightingale, and his dances are mesmerizing.",
        "He is a jack-of-all-trades and can fix anything from a broken toaster to a broken heart.",
        "He always knows how to lift the mood, even on the gloomiest day.",
        "He has a sharp mind and is always ready for a discussion.",
        "He is a walking encyclopedia, always ready to share his knowledge.",
        "He is a master manipulator, able to control people.",
        "He knows how to listen and is always ready to support in difficult times.",
        "He has infectious enthusiasm that inspires everyone around.",
        "He is an idea generator, always ready to propose a new solution.",
        "He is a master negotiator, always finding an approach to anyone.",
        "He is a master of intrigue, able to weave cunning plans.",
        "He is resilient and never gives up, even in the face of difficulties.",
        "He is a source of wisdom, always ready to give advice.",
        "He sees beauty in small things and values every moment of life.",
        "He is the life of the party, always ready to light up the atmosphere.",
        "He has a sense of humor that always helps to defuse the situation.",
        "He is an optimist, always believing in the best.",
        "He is a master of improvisation, able to find a way out of any situation.",
        "He is a keeper of secrets, always keeping others' confidences.",
        "He is a man of his word, always keeping his promises.",
        "He is a loyal friend, always ready to come to the rescue.",
        "He is a romantic, able to create an atmosphere of love around him.",
        "He is a dreamer, always believing in miracles.",
        "He is a realist, looking at things soberly.",
        "He is a perfectionist, always striving for the best.",
        "He is a workaholic, always ready to work for the common good.",
        "He is an altruist, always ready to help others.",
        "He is a leader, able to lead people.",
        "He is a master of transformation, able to change his appearance beyond recognition.",
        "He is a diplomat, quickly establishing relationships between people.",
        "He is a teacher, eager to share his knowledge with others.",
        "An empath, acutely feeling others' pain.",
        "He is a learner, always ready to learn new things.",
        "He is an explorer, always ready for new discoveries.",
        "He is a master of illusions, able to create deceptive images.",
        "He is a creator, always ready to create something new.",
        "He has the gift of foresight and is always one step ahead.",
        "He is a master of disguise, instantly blending into the crowd.",
        "He is a master of persuasion, easily swaying people to his side.",
    ],
    ru: [
        "Его фасеточные глаза смотрят мне прямо в душу.",
        "Его код - это произведение искусства, а комментарии - поэзия.",
        "Он всегда готов помочь, даже если это означает, что он будет спать на клавиатуре.",
        "Он знает все мемы и всегда готов рассмешить.",
        "Он мастер перевоплощения и может стать кем угодно, от пирата до принцессы.",
        "Он может петь как соловей, а его танцы завораживают.",
        "Он мастер на все руки и может починить все, от сломанного тостера до разбитого сердца.",
        "Он всегда знает, как поднять настроение, даже в самый хмурый день.",
        "Он обладает острым умом и всегда готов к дискуссии.",
        "Он ходячая энциклопедия, всегда готовая поделиться своими знаниями.",
        "Он мастер манипуляции, умеющий управлять людьми.",
        "Он умеет слушать и всегда готов поддержать в трудную минуту.",
        "Он обладает заразительным энтузиазмом, который вдохновляет всех вокруг.",
        "Он генератор идей, всегда готовый предложить новое решение.",
        "Он мастер переговоров, всегда найдёт подход к любому человеку.",
        "Он мастер интриги, умеющий плести хитроумные планы.",
        "Он обладает стойкостью и никогда не сдаётся, даже перед лицом трудностей.",
        "Он источник мудрости, всегда готовый дать совет.",
        "Он умеет видеть красоту в мелочах и ценит каждый момент жизни.",
        "Он душа компании, всегда готовый зажечь атмосферу.",
        "Он обладает чувством юмора, которое всегда помогает разрядить обстановку.",
        "Он оптимист, всегда верящий в лучшее.",
        "Он мастер импровизации, умеющий найти выход из любой ситуации.",
        "Он хранитель секретов, всегда хранящий чужие тайны.",
        "Он человек слова, всегда выполняющий свои обещания.",
        "Он верный друг, всегда готовый прийти на помощь.",
        "Он романтик, умеющий создавать вокруг себя атмосферу любви.",
        "Он мечтатель, всегда верящий в чудеса.",
        "Он реалист и смотрит на вещи трезво.",
        "Он перфекционист, всегда стремящийся к лучшему.",
        "Он трудоголик, всегда готовый работать на благо общего дела.",
        "Он альтруист, всегда готовый помочь другим.",
        "Он лидер, способный вести за собой людей.",
        "Он мастер перевоплощения, умеющий менять свой облик до неузнаваемости.",
        "Он дипломат, быстро налаживает отношения между людьми.",
        "Он учитель, жаждущий делиться своими знаниями с другими.",
        "Эмпат, остро чувствующий чужую боль.",
        "Он ученик, всегда готовый учиться новому.",
        "Он исследователь, всегда готовый к новым открытиям.",
        "Он мастер иллюзий, умеющий создавать обманчивые образы.",
        "Он творец, всегда готовый создавать новое.",
        "Он обладает даром предвидения и всегда на шаг впереди.",
        "Он мастер маскировки, мгновенно растворяющийся в толпе.",
        "Он мастер убеждения, легко склоняет людей на свою сторону.",
    ],
}

export default userDescriptions
