import { i18n } from "@lingui/core"

export type SupportedLocale = "en" | "ru"

export default function initTranslations(): void {
    i18n.load("en", {
        setUsernameToConnect: "Set a username to connect to the room.",
        enterRoomId: "Enter room ID.",
        suchRoomWasNotFound: "Such room was not found.",
        someoneWithSuchNameOrPasscodeAlreadyInRoom: "Someone with such name or passcode is already in the room.",
        rejectedBcOfUsernameIsTooLong: "They say your username is too long, try a shorter one.",
        youAreBannedInTheRoom: "You are banned in this room.",
        couldNotConnectToTheRoom: "Oops, couldn't connect to the room for some reason.",
        thxForUsingYourOwnApiKey: "Thank you for using your own API key! ❤️",
        youWereBannedInTheRoom: "You were banned in this room.",
        lightOrDark: "Light or dark",
        loudOrQuiet: "Loud or quiet",
        language: "Language",
        somethingBadHappened: "Oops, something bad happened!",
        returnHome: "Return home",
        usernameCannotBeEmpty: "Username cannot be empty.",
        usernameIsTooLong: "Username is too long.",
        passcodeIsMandatory: "Passcode is mandatory. You can get one in our ",
        passcodeIsMandatory2: "Discord",
        passcodeCheckInProgress: "Checking...",
        passcodeDecodingFailedBecauseServerIsDown: "Cannot read the passcode while the server is down.",
        passcodeDecodingFailed: "Couldn't decode the passcode.",
        useOwnApiKey: "Use my own",
        useOwnApiKeyDescription:
            "Create your own key in the Google Developer Console as described below in the 'About API Key' section and use it.",
        doNotUseApiKey: "Don't use one at all",
        doNotUseApiKeyDescription:
            "The map will have inverted colors, but you won't need to create a key and the developer key quota of this wonderful site won't be spent.",
        useDefaultApiKey: "Use the default one",
        useDefaultApiKeyDescription:
            "If you absolutely can't create your own key but still want to play, feel free to use this option.",
        tryToReloadThePage: "Something went wrong... try reloading the page.",
        oopsSomethingIsWrongWithApiKeyStrategy: "No-no, something's not right!",
        userSettings: "User settings",
        username: "Username",
        howToCallYou: "How should we call you?",
        passcode: "Passcode",
        passcodePlaceholder: "Quite a long string like eyJhbGciOiJIUzI1NiIsI...",
        whatDoWeDoWithTheApiKey: "What do we do with the API key?",
        apiKey: "API key",
        apiKeyInputPlaceholder: "Key for Google Maps JS API",
        aboutApiKeyTitle: "About API key",
        aboutApiKeyBeforeInstruction:
            "The API key is not mandatory, but if you can, please use your own key. Here is the ",
        aboutApiKeyInstruction: "instruction",
        aboutApiKeyAfterInstruction1:
            " on how to create and set up a key from the Geohub developers (requires a Google account with a linked card in the developer console).",
        aboutApiKeyAfterInstruction2:
            " If you just want to explore, there's an option to not use a key at all. In this case, the map will have inverted colors.",
        aboutApiKeyAfterInstruction3:
            " The API key is only stored in your browser and is not sent to the server, honestly. Thank you!",
        connectToExistingRoom: "Connect to an existing room",
        roomId: "Room ID",
        roomIdPlaceholder: "9F79fsv5iO or something like that...",
        connect: "Connect",
        createNewRoom: "Create a new room",
        create: "Create",
        chooseYourAvatar: "Choose your avatar",
        serverIsUnreachable: "The server is unreachable, you won't be able to play for now.",
        gameFinishedTheWinnerIs: "The game is over! The winner is...",
        cool: "Cool!",
        connectionWorksWell: "Connection is working fine.",
        connectionLost: "Connection lost.",
        me: "me",
        submitGuess: "Submit guess",
        revokeGuess: "Revoke guess",
        startRound: "Start round",
        doYouREallyWannaExitTheRoom: "Are you sure you want to leave the room?",
        shyNo: "No...",
        yesPlease: "Yes, please!",
        hello: "Hello!",
        hereIsAnInvitationLink: "Here is a link to invite someone:",
        copy: "Copy",
        howToPlayQuestion: "How to play?",
        howToPlay:
            "When the room host starts the game, a street view panorama and a countdown timer appear on the screen. Before the timer ends, you need to place a marker on the map at the bottom right. After the timer ends, the round ends and players are awarded points based on the proximity of their marker to the actual location of the panorama. And so on in a circle.",
        gotIt: "Got it.",
        host: "host",
        tagInTheChat: "Tag in the chat",
        changeScore: "Change score",
        mute: "Mute",
        unmute: "Unmute",
        ban: "Ban",
        doYouReallyWantToBan: "Do you really want to ban",
        oopsNo: "Oops, no...",
        strongYes: "Yes!",
        changingUserScore: "Changing user score",
        backIChangedMyMind: "Back, I changed my mind",
        goAhead: "Go ahead!",
        cannotPasteImage: "You can only attach up to 4 images.",
        lightTheme: "Light",
        darkTheme: "Dark",
        systemTheme: "As in system",
    })
    i18n.load("ru", {
        setUsernameToConnect: "Установи юзернейм чтобы подключиться к комнате.",
        enterRoomId: "Введи айди комнаты.",
        suchRoomWasNotFound: "Такая комната не найдена.",
        someoneWithSuchNameOrPasscodeAlreadyInRoom: "Кто-то с таким именем или пасскодом уже есть в комнате.",
        rejectedBcOfUsernameIsTooLong: "Говорят что твой юзернейм слишком длинный, попробуй покороче.",
        youAreBannedInTheRoom: "Ты забанен в этой комнате.",
        couldNotConnectToTheRoom: "Ой, почему-то не получилось подключиться к комнате.",
        thxForUsingYourOwnApiKey: "Спасибо за использование собственного АПИ ключа! ❤️ ",
        youWereBannedInTheRoom: "Тебя забанили в этой комнате.",
        lightOrDark: "Светло или темно",
        loudOrQuiet: "Громко или тихо",
        language: "Язык",
        somethingBadHappened: "Ой-ой, произошло что-то нехорошее!",
        returnHome: "Вернуться домой",
        usernameCannotBeEmpty: "Юзернейм не может быть пустым.",
        usernameIsTooLong: "Юзернейм слишком длинный.",
        passcodeIsMandatory: "Пасскод обязателен. Его можно получить в нашем ",
        passcodeIsMandatory2: "Дискорде",
        passcodeCheckInProgress: "Проверяем...",
        passcodeDecodingFailedBecauseServerIsDown: "Невозможно считать пасскод пока сервер недоступен.",
        passcodeDecodingFailed: "Не получилось считать пасскод.",
        useOwnApiKey: "Используем свой",
        useOwnApiKeyDescription:
            "Создай свой ключ в консоли разработчика гугла как описано ниже в разделе «Про АПИ ключ» и используй его.",
        doNotUseApiKey: "Не используем вообще",
        doNotUseApiKeyDescription:
            "Карта будет с инвертированными цветами, зато не нужно создавать ключ и квота использования ключа разработчика этого замечательного сайта тоже не будет тратиться.",
        useDefaultApiKey: "Используем дефолтный",
        useDefaultApiKeyDescription:
            "Если у тебя совсем нет возможности создать свой ключ, а поиграть хочется, то не стесняйся использовать эту опцию.",
        tryToReloadThePage: "Случилось что-то не то... попробуй перезагрузить страницу.",
        oopsSomethingIsWrongWithApiKeyStrategy: "Нет-нет, это что-то не то!",
        userSettings: "Настройки пользователя",
        username: "Юзернейм",
        howToCallYou: "Как к тебе обращаться?",
        passcode: "Пасскод",
        passcodePlaceholder: "Довольно длинная строка, например, eyJhbGciOiJIUzI1NiIsI...",
        whatDoWeDoWithTheApiKey: "Что делаем с АПИ ключом?",
        apiKey: "АПИ ключ",
        apiKeyInputPlaceholder: "Ключик от Google Maps JS API",
        aboutApiKeyTitle: "Про АПИ ключ",
        aboutApiKeyBeforeInstruction:
            "АПИ ключ не обязателен, но если у тебя есть возможность, то используй, пожалуйста, свой ключ. Вот ",
        aboutApiKeyInstruction: "инструкция",
        aboutApiKeyAfterInstruction1:
            " по созданию и настройке ключа от разработчиков Geohub (требуется гугл аккаунт с подключённой картой в консоли разработчика).",
        aboutApiKeyAfterInstruction2:
            " Если хочется просто осмотреться, то есть опция не использовать ключ вообще. В этом случае карта будет с инвертированными цветами.",
        aboutApiKeyAfterInstruction3:
            " АПИ ключ сохраняется только в твоём браузере и не передаётся на сервер, честное слово. Спасибо!",
        connectToExistingRoom: "Подключиться к существующей комнате",
        roomId: "Айди комнаты",
        roomIdPlaceholder: "9F79fsv5iO или что-то похожее...",
        connect: "Подключиться",
        createNewRoom: "Создать новую комнату",
        create: "Создать",
        chooseYourAvatar: "Выбери себе аватарку",
        serverIsUnreachable: "Сервер недоступен, пока что поиграть не получится.",
        gameFinishedTheWinnerIs: "Игра завершена! Победитель это...",
        cool: "Круто!",
        connectionWorksWell: "Соединение работает нормально.",
        connectionLost: "Соединение потеряно.",
        me: "я",
        submitGuess: "Подтвердить ответ",
        revokeGuess: "Отменить ответ",
        startRound: "Начать раунд",
        doYouREallyWannaExitTheRoom: "Точно хочешь выйти из комнаты?",
        shyNo: "Нет...",
        yesPlease: "Да, и поскорее!",
        hereIsAnInvitationLink: "Вот ссылка по которой сюда можно кого-нибудь пригласить:",
        copy: "Копировать",
        hello: "Привет!",
        howToPlayQuestion: "А как играть?",
        howToPlay:
            "Когда хозяин комнаты начинает игру, на экране появляется стрит вью панорама и таймер обратного отсчёта. До конца таймера нужно поставить метку на карте внизу справа. После конца таймера раунд заканчивается и игрокам начисляются очки пропорционально близости их метки к реальному положению панорамы. И так по кругу.",
        gotIt: "Понятно.",
        host: "хост",
        tagInTheChat: "Тэгнуть в чате",
        changeScore: "Изменить очки",
        mute: "Замьютить",
        unmute: "Размьютить",
        ban: "Забанить",
        doYouReallyWantToBan: "Точно хочешь забанить",
        oopsNo: "Ой, нет...",
        strongYes: "Да!",
        changingUserScore: "Изменение количества очков",
        backIChangedMyMind: "Назад, я передумал",
        goAhead: "Вперёд!",
        cannotPasteImage: "Нельзя прикрепить больше чем 4 картинки.",
        lightTheme: "Светло",
        darkTheme: "Темно",
        systemTheme: "Как в системе",
    })
}
